name: run predict.py

on:
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4  # Checkout the repo content to GitHub runner

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt

      - name: Execute Python script
        run: python score.py  # Ensure score.py is in the repo

      - name: Commit files if changes exist
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git diff --quiet || git commit -m "updated logs"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
